name: Test site build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode clean test
      - name: Archive generated site
        uses: actions/upload-artifact@v5
        with:
            name: generated-site
            path: ./target/roq/
